### ISSUE TITLE
Attempted to fetch annotator "parse" before the annotator pool was created!

### ISSUE THREAD

**Issue by soraby** [stanfordnlp/CoreNLP#381] opened 2017-03-10 23:22 UTC
Running CoreNLP 3.7.0 server using Python, getting this error message for seemingly arbitrary inputs?

`[pool-2-thread-2] ERROR edu.stanford.nlp.pipeline.StanfordCoreNLP - Attempted to fetch annotator "parse" before the annotator pool was created!
java.util.concurrent.ExecutionException: java.lang.AssertionError: Failed to get parser - this should not be possible
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:603)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: Failed to get parser - this should not be possible
	at edu.stanford.nlp.dcoref.RuleBasedCorefMentionFinder.getParser(RuleBasedCorefMentionFinder.java:453)
	at edu.stanford.nlp.dcoref.RuleBasedCorefMentionFinder.parse(RuleBasedCorefMentionFinder.java:443)
	at edu.stanford.nlp.dcoref.RuleBasedCorefMentionFinder.findSyntacticHead(RuleBasedCorefMentionFinder.java:334)
	at edu.stanford.nlp.dcoref.RuleBasedCorefMentionFinder.findHead(RuleBasedCorefMentionFinder.java:272)
	at edu.stanford.nlp.dcoref.RuleBasedCorefMentionFinder.extractPredictedMentions(RuleBasedCorefMentionFinder.java:98)
	at edu.stanford.nlp.pipeline.DeterministicCorefAnnotator.annotate(DeterministicCorefAnnotator.java:117)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:605)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.lambda$handle$358(StanfordCoreNLPServer.java:585)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler$$Lambda$44/1829860859.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 `

**Comment by J38** [comment] 2017-03-10 23:25
Hi I had two questions.  One, what command did you use to start the server, and two, what circumstances caused this error?  Was this after you sent a request to the server?  If so, could you please provide the command you issued to make the request.  Thanks!

**Comment by soraby** [comment] 2017-03-10 23:33
To start the server:
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer

The annotators are loaded in this order:
'pos,depparse,parse,coref,ner,sentiment'

The error comes up within a sequence of requests sent to the server since it was started, so not necessarily the first request. We are calling it through pycorenlp. We were using the same method with version 3.6 and didn't get this crash.

**Comment by Motwani** [comment] 2017-03-26 17:40
I'm also facing this issue.

This is the command I've run to start the server.

java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000

Sending a post request with pycorenlp library. The crashes seem to happen randomly over many requests. Any fixes?

**Comment by J38** [comment] 2017-04-07 02:07
I'm not sure what is happening here.  I guess the first thing I will try is to send a huge amount of queries to the server and see if I can make this happen.

**Comment by J38** [comment] 2017-04-07 02:13
@Motwani are you also getting this error caused by 

`edu.stanford.nlp.dcoref.RuleBasedCorefMentionFinder.getParser(RuleBasedCorefMentionFinder.java:453) `

**Comment by J38** [comment] 2017-04-07 02:41
@Motwani, @soraby are you always issuing the exact same request (except for changing the text) when this is happening?  Or are you also changing some properties of the requests.

**Comment by Motwani** [comment] 2017-04-07 08:54
@J38 it **always** happens when I add the property `'coref.algorithm': 'neural'` and doesn't happen when I'm using the default deterministic model. I don't think it is an issue with the quotes in the text - as the text I'm running contains quotes.

**Comment by pwichmann** [comment] 2017-04-11 02:50
Same problem as OP here.

**Comment by pwichmann** [comment] 2017-05-07 03:52
Kind of sad that this issue does not seem to get any attention - even after 2 months.

**Comment by gangeli** [comment] 2017-05-07 06:45
I agree with the message in the assert: this should not be possible. There are two cases where we'd see that assert: (1) if the annotator pool were never initialized -- e.g., if we called the coref annotator outside of a StanfordCoreNLP pipeline object. Or, (2) if someone called `StanfordCoreNLP.clearAnnotatorPool()` -- which is called only from the coref training code. I've replaced the `pool = null` line with `pool.clear()` and put in a log statement in case that's the bug.

Can anyone replicate the bug with some deterministic minimal failure case?

**Comment by J38** [comment] 2017-05-07 09:13
The issue is that when the StanfordCoreNLP server builds StanfordCoreNLP pipelines, the StanfordCoreNLP static AnnotatorPool is never set and is always null.  I can fix this bug by adding a `StanfordCoreNLP.pool = pool` on line 310 of StanfordCoreNLPServer.java ...I am still pondering the ramifications of doing that.

**Comment by J38** [comment] 2017-05-07 09:52
This issue should be fixed now.  If anyone is still seeing it please let me know.

**Closed by J38** 2017-05-07 09:52 UTC

**Comment by bohemia420** [comment] 2017-05-09 16:33
I just faced this, it was working just fine, only when at one fine moment it started throwing this : 
java.util.concurrent.ExecutionException : java.lang.AssertionError: Failed to get parser - this should not be possible

Still wondering how that happened, all of a sudden? even restarting the server didnt help.

**Comment by bohemia420** [comment] 2017-05-10 03:49
I have cloned the master, but I am confused how to run the standalone webserver. Could you please tell us how to run the corenlp webserver on local?

**Comment by bohemia420** [comment] 2017-05-10 04:32
197NODMB16623:CoreNLP sumit$ java -mx4g -cp "*" edu/stanford/nlp/pipeline/StanfordCoreNLPServer -port 9000 -timeout 15000
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer

197NODMB16623:CoreNLP sumit$ java -mx4g -cp ".//target/classes/" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000
--- StanfordCoreNLPServer#main() called ---
setting default constituency parser
warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
to use shift reduce parser download English models jar from:
http://stanfordnlp.github.io/CoreNLP/download.html
    Threads: 4
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/pipeline/demo/corenlp-brat.html" as class path, filename or URL
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1326)
Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/pipeline/demo/corenlp-brat.html" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:637)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$FileHandler.<init>(StanfordCoreNLPServer.java:499)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$FileHandler.<init>(StanfordCoreNLPServer.java:496)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1324)
CoreNLP Server is shutting down.

I think it's some classpath issue here.

**Comment by baxterai** [comment] 2017-05-20 06:54
The mod introduced by J38 appears to work (7 May 2017). To rebuild stanford-corenlp-3.7.0 with the patch (code copied from https://github.com/stanfordnlp/CoreNLP/commit/92363c1766c27ff5c782dbf4d1c9cf85815d2212):
- install ant (e.g. sudo apt-get install ant)
- assume stanford-corenlp-full-2016-10-31.zip has been unzipped to [LOCATION]/stanford-corenlp-full-2016-10-31 (this folder contains stanford-corenlp-3.7.0-sources.jar)
- unzip stanford-corenlp-3.7.0-sources.jar contents to [LOCATION]/stanford-corenlp-full-2016-10-31/src/
- cd [LOCATION]/stanford-corenlp-full-2016-10-31/src/edu/stanford/nlp/pipeline/
- create a backup of StanfordCoreNLPServer.java (e.g. cp StanfordCoreNLPServer.java StanfordCoreNLPServer.java.orig)
- edit StanfordCoreNLPServer.java and insert these two lines of code (line 273);
```
	      impl = pipelineCache.get(props);
	       if (impl == null) {
        	 AnnotatorPool pool = StanfordCoreNLP.constructAnnotatorPool(props, new AnnotatorImplementations());
	+        // TO DO: this might cause some problems
	+        StanfordCoreNLP.pool = pool;
        	 impl = new StanfordCoreNLP(props, pool);
        	 pipelineCache.put(props, impl);
	       }	
```		
- cd [LOCATION]/stanford-corenlp-full-2016-10-31
- create a backup of stanford-corenlp-3.7.0.jar (e.g. mv stanford-corenlp-3.7.0.jar stanford-corenlp-3.7.0.jar.orig)
- ant
- cd classes/
- jar -cf ../stanford-corenlp-3.7.0.jar edu

**Comment by andrewufrank** [comment] 2017-06-01 10:55
i had the same error message and identified a single apostroph (for a possessiv - i.e. bird's) as the cause. AFTER parsing a sentence with 'bird's` the NEXT call to the server gives the reported error: 

```
callHTTP6 error caught 7 callHTTP6 returns code (5,0,0) java.util.concurrent.ExecutionException: java.lang.AssertionError: Failed to get parser - this should not be possible for request 
 POST http://nlp.gerastree.at:9000/?annotators=tokenize%2Cssplit%2Cpos%2Clemma%2Cner%2Cdepparse%2Cdcoref&outputFormat=xml HTTP/1.1
Accept: */*
Content-Length: 526
Content-Type: text/plain
```

the proposed fix seems to work even in this case (but i guess from the code, that some more fixing could be required). 
Thank you for the excellent and detailed description on how to apply the fix - i have no experience with java code and it worked. my only point of doubt was, whether the `+` signs should be included or not - i did not include them, assuming they were produce by diff).
