### ISSUE TITLE
Speed of coreNLP very slow, any tuning advice?

### ISSUE THREAD

**Issue by gravin** [stanfordnlp/CoreNLP#420] opened 2017-04-26 04:30 UTC
for this file, CoreNLP-chinese.properties
i only used 3 annotators 
annotators = tokenize, ssplit, pos
#, lemma, ner, parse, mention, coref

but speed is (pipeline.timingInformation())
TOTAL: 11.3 sec. for 32105 tokens at 2830.6 tokens/sec.
TOTAL: 0.3 sec. for 23 tokens at 68.7 tokens/sec.
TOTAL: 17.6 sec. for 69637 tokens at 3951.5 tokens/sec.
TOTAL: 18.1 sec. for 73458 tokens at 4049.3 tokens/sec.

as some other tools like mmseg4j  aclaiming 1200 KB/s to 1900 KB/s
does corenlp have a performance bottleneck or need some other tuning work?

**Comment by gangeli** [comment] 2017-04-26 06:52
It looks like maybe you have to wait for the burn-in time for the JIT, or some similar constant time cost slowing you down. Try running the system for much longer?

Performance tips (and a rough benchmark for how fast things are supposed to run) can be found at: https://stanfordnlp.github.io/CoreNLP/memory-time.html

**Comment by gravin** [comment] 2017-04-26 08:21
i let my crawler program running for a period, mostly it is 

 (pipeline.timingInformation())
Annotation pipeline timing information:
TokenizerAnnotator: 20.1 sec.
WordsToSentencesAnnotator: 0.1 sec.
POSTaggerAnnotator: 11.8 sec.
TOTAL: 31.9 sec. for 188951 tokens at 5915.4 tokens/sec.

(calculated by myself)
total length9922total time consumed:111

the speed is around  5915.4 tokens/sec, cant reach 1 million/sec as your link.

and for my crawler program, it will be running in multiple threads, should all threads using one StanfordCoreNLP instance or one thread using one? the test is done through one shared pipeline instance.

**Comment by gangeli** [comment] 2017-04-27 04:01
Can you run the program single-threaded, with >1gb of memory, for a longer period of time (e.g., 10+ minutes)? How many tokens do you have per document, roughly?

**Comment by gravin** [comment] 2017-04-27 07:22
my small test program is here(https://github.com/gravin/nlp_test)
 just make sure you have this folder F:\data\
and run CrawlerWithNLPTest 

it will crawel http://www.gov.cn/  and write poc result to F:\data\nlp folders

i run this for a period with 3g memory,  but the speed is still very slow

URL: http://www.gov.cn/xinwen/2016-07/15/content_5091396.htm filename:756b9374-4144-492d-b0de-5d2c9290328f
corenlp total length2251 total time consumed:123
ansj    total length2251 total time consumed:1
URL: http://www.gov.cn/xinwen/2017-04/17/content_5186432.htm filename:da4951e8-f283-4627-8f4c-e7fedfcfa837
corenlp total length1941 total time consumed:81
ansj    total length1941 total time consumed:2
URL: http://www.gov.cn/xinwen/2017-04/03/content_5183151.htm filename:dc8e3fb7-a5e4-4613-bb92-809770c1e0de
corenlp total length1802 total time consumed:71
ansj    total length1802 total time consumed:1

**Comment by gangeli** [comment] 2017-04-27 19:13
Ah, is this in Chinese? I believe the Chinese segmenter is actually running a sequence model under the hood, which would explain the slow runtime. Whereas the English tokenizer is a much faster rule-based lexer.

Unfortunately, there's not much that can be done about this as far as I know. Others are welcome to jump in if they have suggestions.

**Comment by gravin** [comment] 2017-04-28 02:10
yes, its in chinese.

**Comment by gangeli** [comment] 2017-04-28 03:21
OK, then I'm going to close this as "expected behavior." I don't think there's anything to be done that would make a substantial difference in performance, but if others have ideas they should suggest them.

**Closed by gangeli** 2017-04-28 03:21 UTC
