### ISSUE TITLE
TokensRegex cannot detect rules cross the period '.' 

### ISSUE THREAD

**Issue by lilyclemson** [stanfordnlp/CoreNLP#1396] opened 2023-11-16 19:59 UTC
The task is to detect apartment number via tokensRegex.

Example sentence: I live in 123 Pretty RD, APT. #456.
Here is the rule used to detect the apartment number: { ruleType: "tokens", pattern: ( /APT/ /\./ /#/ [{word:/[0-9]+/}]), action: Annotate($0, ner, "APT#"), result:"APARTMENT NUMBER"}

Above rule failed to detect the pattern APT. #456. It looks like TokensRegex cannot correctly recognize the rule across the period '.'

 A guess is a change in line 713 would do the trick …

[https://github.com/stanfordnlp/CoreNLP/blob/main/src/edu/stanford/nlp/process/PTBLexer.flex](url)

**Comment by AngledLuffa** [comment] 2023-11-16 20:57
That's an excellent guess, and in fact that's the first place I went to when trying to diagnose this.  The problem is clearly that the tokenizer is splitting this into two sentences rather than keeping it as one.  However, despite having `Apt` with that exact capitalization in the abbreviation list there, the tokenizer is actually case-insensitive to those abbreviations.  Here are a couple examples:

```
I lived at APT. 303 for many years     ... one sentence
I lived at APT. #303 for many years    .... two sentences
I lived at Apt. 303 for many years     ... one sentence
I lived at Apt. #303 for many years    ... two sentences
```

My belief is that we need to add `#` as a token that can follow `ABBREV3`, at which point it will work as desired.  In the meantime, if you happen to be using data of sentence each, you can always use the options that force the tokenizer to produce exactly one sentence per query.

https://github.com/stanfordnlp/CoreNLP/blob/f8838d2639589f684cbaa58964cb29db5f23df7f/src/edu/stanford/nlp/process/PTBLexer.flex#L748

**Comment by lilyclemson** [comment] 2023-11-17 21:40
Thank you for the fix and quick response!

**Comment by lilyclemson** [comment] 2024-01-12 18:53
Hi @AngledLuffa, I wonder if @manning had a chance to see if we can merge the current fix? Thank you.

**Comment by AngledLuffa** [comment] 2024-01-12 19:28
It's already merged.  I can make a new release that includes it soon if you need, or you can just use the dev branch

**Comment by lilyclemson** [comment] 2024-01-12 19:43
> It's already merged. I can make a new release that includes it soon if you need, or you can just use the dev branch

That would be great if we can have a release version of it. Thanks very much for the quick response!

**Comment by AngledLuffa** [comment] 2024-01-13 03:13
It's not an official release yet, but I built a version here:

https://nlp.stanford.edu/software/stanford-corenlp-4.5.5b.zip

I'd like to make some more changes before making an official release

**Comment by lilyclemson** [comment] 2024-01-23 20:18
Thanks very much for the release. Looking forward to the official release as well.

**Comment by AngledLuffa** [comment] 2024-02-01 20:56
Now released in 4.5.6 (may take a little time to show up on Maven)

**Closed by AngledLuffa** 2024-02-01 20:56 UTC

**Comment by lilyclemson** [comment] 2024-02-01 20:58
Thanks so much! I appreciate it @AngledLuffa

**Comment by lilyclemson** [comment] 2024-07-15 20:16
Hi
