### ISSUE TITLE
Remove old TokensRegexNER file and references to it

### ISSUE THREAD

**Issue by manning** [stanfordnlp/CoreNLP#563] opened 2017-11-06 00:56 UTC
Our code still refers to and has a DefaultPaths to `type_map_clean`, but it's really our tackbp2010 regexner. We should everywhere change to the two current files - currently in `kbp/regexner_* but they should maybe be moved out of the kbp dir.

**Comment by J38** [comment] 2017-11-07 00:25
Should RegexNERAnnotator be deprecated ?  Currently `regexner` points to `TokensRegexNERAnnotator`.  This situation could cause some confusion.  I assume you would always want to use TokensRegexNERAnnotator over RegexNERAnnotator.  

Furthermore for 3.9.0 we should make sure include those in the main models jar.

**Comment by J38** [comment] 2017-11-07 01:13
Wait, they already are in the default models jar, oops!

**Comment by J38** [comment] 2017-12-14 06:14
I am going to remove RegexNERAnnotator since it is a duplicate of TokensRegexNERAnnotator

**Comment by J38** [comment] 2017-12-14 06:19
Err, maybe I won't do that actually!

**Closed** 2017-12-24 10:02 UTC
