### ISSUE TITLE
How to start a CoreNLP Server to segment Chinese text?

### ISSUE THREAD

**Issue by Gwill** [stanfordnlp/CoreNLP#165] opened 2016-03-29 10:35 UTC
I started a CoreNLP Server with:
```
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -props StanfordCoreNLP-chinese.properties -port 9000
```

and

```
wget --post-data '直观地表明这种数据结构如何简化应用程序的处理时间和复杂性。' 'localhost:9000/?properties={"annotators": "tokenize,ssplit,pos","outputFormat": "json"}' -O -
```

the response is:

```
{"sentences":[{"index":0,"parse":"SENTENCE_SKIPPED_OR_UNPARSABLE","basic-dependencies":[{"dep":"ROOT","governor":0,"governorGloss":"ROOT","dependent":2,"dependentGloss":"。"},{"dep":"compound","governor":2,"governorGloss":"。","dependent":1,"dependentGloss":"直观地表明这种数据结构如何简化应用程序的处理时间和复杂性"}],"collapsed-dependencies":[{"dep":"ROOT","governor":0,"governorGloss":"ROOT","dependent":2,"dependentGloss":"。"},{"dep":"compound","governor":2,"governorGloss":"。","dependent":1,"dependentGloss":"直观地表明这种数据结构如何简化应用程序的处理时间和复杂性"}],"collapsed-ccprocessed-dependencies":[{"dep":"ROOT","governor":0,"governorGloss":"ROOT","dependent":2,"dependentGloss":"。"},{"dep":"compound","governor":2,"governorGloss":"。","dependent":1,"dependentGloss":"直观地表明这种数据结构如何简化应用程序的处理时间和复杂性"}],"openie":[],"tokens":[{"index":1,"word":"直观地表明这种数据结构如何简化应用程序的处理时间和复杂性","originalText":"直观地表明这种数据结构如何简化应用程序的处理时间和复杂性","lemma":"直观地表明这种数据结构如何简化应用程序的处理时间和复杂性","characterOffsetBegin":0,"characterOffsetEnd":28,"pos":"NN","ner":"O","speaker":"PER0","before":"","after":""},{"index":2,"word":"。","originalText":"。","lemma":"。","characterOffsetBegin":28,"characterOffsetEnd":29,"pos":"SYM","ner":"O","speaker":"PER0","before":""}
```

it is not work.

**Comment by J38** [comment] 2016-04-04 04:11
I think you need to send all of the properties in StanfordCoreNLP-chinese.properties in the json in your wget request.  The issue is currently the server doesn't seem to work with custom annotators, and currently Chinese segmentation is handled by a custom annotator.  I will look into this more and I think we should be able to push a fix for this so the server can be used on Chinese text.  Thanks for raising the issue!

**Comment by stellasia** [comment] 2016-06-16 13:01
Hello!

I had the same issue (with the server not using the French models despite the `-prop` flag) and repeating the properties in `wget` perfectly worked (thanks  @J38 for the trick!)

I was just wondering what the status was about the configuration of "not-english" models? Also is there a chance to have it (other models)  working in the UI?

Thank you.

**Comment by jumboalex** [comment] 2016-06-21 08:06
Quick question, if I add the "segment" into the source code default properties, and rebuild the jar file, would that work for Chinese?  I'm getting the similar issue, and furthermore the Chinese characters cannot display in the output html.  (Well I set everything the same as above)

**Comment by vache** [comment] 2016-06-29 19:38
What is the status of this?  I've tried this with the chinese properties passed in the URL with no luck.  Is there any other workaround at the moment?

**Comment by rudaoshi** [comment] 2016-07-10 11:34
You should write a server that accept a custom properties. Current server of corenlp 3.6 works in a stupid way, since one hardly changes their requirements on nlp components. 

I wrote my own server:  https://gist.github.com/rudaoshi/33f6efeee23a72fe565f8e33af0873a9 

I'm glad if you find it helpful.

**Comment by aqppe** [comment] 2016-09-05 05:55
guys, could you give a example using  wget...
stellasia could you give the example you used.

**Comment by stellasia** [comment] 2016-09-05 07:56
@aqppe, you can find the wget command I finally used in [this SO answer](http://stackoverflow.com/questions/37838374/running-stanford-corenlp-server-with-french-models/37856260#37856260)

**Comment by juvaud** [comment] 2016-09-28 13:08
I have troubles to get the server running for Chinese, as the server tells me that it doesn't find the segmenter, which is defined in the properties file. Somebody got it running for Chinese explicitly?

**Comment by J38** [comment] 2016-10-17 02:06
I'll repeat my answer from a different issue:

This issue has now been resolved in the current version of the code. If you enter a command like this:

wget --post-data '<insert Chinese text here>' 'localhost:9000/?properties={"pipelineLanguage":"zh", "outputFormat":"json"}' -O - the server will load the appropriate Chinese resources.

**Closed by J38** 2016-10-17 02:06 UTC

**Comment by unhandyandy** [comment] 2016-11-13 21:38
I'm finding that when I run 
`wget --post-data '' 'localhost:9000/?properties={"pipelineLanguage":"zh", "outputFormat":"json"}' -O - `
the server crashes while loading the coref annotator.

**Comment by hezhenghao** [comment] 2016-12-13 08:30
When I use:
`wget --post-data '' 'localhost:9000/?properties={"pipelineLanguage":"zh", "outputFormat":"json"}' -O -`
I'm getting this error:
`java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.getProperties(StanfordCoreNLPServer.java:681)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:540)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

Have been struggling with this for quite a while now. Someone please help.

**Comment by fingertap** [comment] 2016-12-26 09:37
It seems that the parsing result returned is not correct. I post a simple sentence and the server just recognized the punctuation.
```shell
wget --post-data '你尝试解释一下这句话好么？' 'localhost:9000/?properties={"pipelineLanguage":"zh", "outputFormat":"json"}' -O - 2>/dev/null
```
The formatted result is:
```json
{
  "sentences": [
    {
      "tokens": [
        {
          "after": "",
          "before": "",
          "pos": "CD",
          "characterOffsetEnd": 9,
          "characterOffsetBegin": 0,
          "originalText": "你可以解释这句话么",
          "word": "你可以解释这句话么",
          "index": 1
        },
        {
          "after": "^@^@^@^@^@^@^@^@",
          "before": "",
          "pos": "CD",
          "characterOffsetEnd": 10,
          "characterOffsetBegin": 9,
          "originalText": "？",
          "word": "？",
          "index": 2
        }
      ],
      "parse": "SENTENCE_SKIPPED_OR_UNPARSABLE",
      "index": 0
    }
  ]
}
```
Use `edu.stanford.nlp.pipeline.StanfordCoreNLP` directly from command line can give correct answers. Above result is obtained under `Stanford-CoreNLP-3.6.0`.

**Comment by henryyang42** [comment] 2017-05-23 08:36
Since we need to pass all the config in ``StanfordCoreNLP-chinese.properties``, the following ugly python snippet may do the job.
```python
from pycorenlp import StanfordCoreNLP
filename = '/Users/henryyang/stanford-corenlp-full-2016-10-31/StanfordCoreNLP-chinese.properties'
properties = {}
with open(filename) as f:
    for line in f.readlines():
        tok = line.split('=')
        if len(tok) == 2:
            properties[tok[0]] = tok[1][:-1]
            
nlp = StanfordCoreNLP('http://localhost:9000')
res = nlp.annotate("过了下午四点，带母亲、肇嘉嫂、淑英等孩子们到天坛游览", properties=properties)
res = json.loads(res)
for sentence in res['sentences']:
    for tok in sentence['tokens']:
        print (tok['word'], tok['ner'])
```

Output:
```
过 O
了 O
下午 MISC
四点 MISC
， O
带 O
母亲 O
、 O
肇嘉嫂 O
、 O
淑英 O
等 O
孩子们 O
到 O
天坛 O
游览 O
```
