### ISSUE TITLE
SEVERE: WARNING: failed to parse sentence. Will continue with the right-most head heuristic:

### ISSUE THREAD

**Issue by denzilc** [stanfordnlp/CoreNLP#459] opened 2017-06-08 20:26 UTC
Here's the error I receive.

> Jun 08, 2017 8:23:52 PM edu.stanford.nlp.ie.machinereading.GenericDataSetReader assignSyntacticHead
> SEVERE: WARNING: failed to parse sentence. Will continue with the right-most head heuristic:

> java.lang.IllegalArgumentException: Input word not tagged
> 	at edu.stanford.nlp.parser.shiftreduce.ShiftReduceParser.initialStateFromTaggedSentence(ShiftReduceParser.java:236)
> 	at edu.stanford.nlp.parser.shiftreduce.ShiftReduceParserQuery.parse(ShiftReduceParserQuery.java:54)
> 	at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:323)
> 	at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:254)
> 	at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:102)
> 	at edu.stanford.nlp.ie.machinereading.GenericDataSetReader.parse(GenericDataSetReader.java:531)
> 	at edu.stanford.nlp.ie.machinereading.GenericDataSetReader.findSyntacticHead(GenericDataSetReader.java:398)
> 	at edu.stanford.nlp.ie.machinereading.GenericDataSetReader.assignSyntacticHead(GenericDataSetReader.java:219)
> 	at edu.stanford.nlp.ie.machinereading.MachineReading.assignSyntacticHeadToEntities(MachineReading.java:655)
> 	at edu.stanford.nlp.ie.machinereading.MachineReading.annotate(MachineReading.java:596)
> 	at edu.stanford.nlp.ie.machinereading.MachineReading.annotate(MachineReading.java:567)
> 	at edu.stanford.nlp.pipeline.RelationExtractorAnnotator.annotate(RelationExtractorAnnotator.java:55)
> 	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
> 	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:605)
> 	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.lambda$handle$0(StanfordCoreNLPServer.java:588)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by manning** [comment] 2017-06-12 03:31
Agreed, there is a bug here that at present you cannot successfully combine the `parse` annotator using the Shift-Reduce constituency parser with the use of the `relation` annotator. We will try to fix this at some point, but for the moment, you'll need to use a different parser (such as the default `englishPCFG` or potentially `kbp` rather than `relation`.

Documentation: you can reproduce this error with:
`java -mx5g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP -file JuliaGillard.txt -outputFormat json -annotators tokenize,ssplit,pos,lemma,ner,parse,relation -parse.model edu/stanford/nlp/models/srparser/englishSR.ser.gz`

**Comment by nairvino** [comment] 2019-11-20 06:24
Hi, Please let me know whether this is fixed as I ran into this error,

**Comment by AngledLuffa** [comment] 2019-11-25 21:00
I can explain what the issue is.  Now I just need to figure out what to fix
it

The relation extractor tries to get a specific span from the parse tree.
If it doesn't find that exact span, it re-parses a fake sentence composed
of a subset of the sentence with some added text in front of it using the
current parse annotator.  The SR Parser requires tags, but the added text
isn't tagged, so it barfs with the very-appropriate
"java.lang.IllegalArgumentException: Input word not tagged" error.

The solution might be as simple as putting the correct tags on the fake
text - it's always the same, so hardcoding the tags should be simple.  I
need to check that the SR Parser is actually suitable for the type of
reparsing it is doing, though, as it also uses ParserConstraint as part of
this operation.

**Comment by AngledLuffa** [comment] 2019-11-25 21:00
*how

**Comment by AngledLuffa** [comment] 2019-11-26 18:39
Update: the SRParser does obey ParserConstraints, so that's not an issue.
Guess the guy who wrote it all those years ago was a pretty cool guy.
Adding the tags is easy enough, but I'm not 100% sure how (or even if) the
tags will change when we update to UD 2.0, which we are doing as part of
the next release.

**Comment by AngledLuffa** [comment] 2019-11-27 08:36
Have pushed a fix.  Will be available in the next release, or you can
integrate this into your sources jar and rebuild:

edu/stanford/nlp/ie/machinereading/GenericDataSetReader.java

**Closed** 2019-11-27 08:37 UTC
Labels: bug

**Comment by nairvino** [comment] 2019-11-29 10:00
Many Thanks, much appreciated.
