### ISSUE TITLE
OpenIE fails for sentence containing the word 'which'

### ISSUE THREAD

**Issue by orangewood2408** [stanfordnlp/CoreNLP#804] opened 2018-11-30 18:59 UTC
When running OpenIE with a document contains the following sentence 'The first is a package for side-loading, followed by launcher and a tool that loads into process memory.' OpenIE crashes with

```
Caused by: java.lang.AssertionError
	at edu.stanford.nlp.naturalli.Util.cleanTree(Util.java:324)
	at edu.stanford.nlp.naturalli.OpenIE.annotateSentence(OpenIE.java:463)
	at edu.stanford.nlp.naturalli.OpenIE.lambda$annotate$2(OpenIE.java:547)
```
If we change the word 'which' to 'and' the error does not occur. 

We use the following settings and are running version 3.9.2:

props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,depparse,coref,natlog,openie");
props.setProperty("coref.algorithm", "statistical");

Any idea how I can workaround this?

Regards,
Avon

**Comment by J38** [comment] 2018-12-04 05:53
The example sentence you have provided does not have the word "which" in it.  I tried your example sentence and replaced the "and" in it with "which", but this did not generate an error.

**Comment by gangeli** [comment] 2018-12-07 08:11
By the looks of it, an easy workaround would be to disable assertions (the `-ea` JVM flag). I'll look into this a bit more when I get a chance. My guess is that it failed to convert the dependency graph into a tree.

**Comment by AngledLuffa** [comment] 2021-12-11 19:37
Seconding what @J38 said all those years ago, this is a rather confusing error report.  However, this is most likely a duplicate of #1082 (yes, I'm accusing the earlier error report of being the duplicate), and there is hopefully a fix available in that thread.

**Closed by AngledLuffa** 2021-12-11 19:37 UTC
Labels: duplicate
