### ISSUE TITLE
Tokenization character offset issue while consuming output

### ISSUE THREAD

**Issue by kunalsawhney** [stanfordnlp/CoreNLP#994] opened 2020-02-10 10:38 UTC
I have a use case where my system is developed in python and internally using corenlp server for annotation. I am using "pycorenlp" python library to access the corenlp server. This was working great until I encountered a case where the token character offsets returned by corenlp (Java) are incompatible with Python. 

Example: 
Consider a string with text : "𝒚̂𝒊".

On running the above text through the corenlp annotation pipeline. The character offsets returned for token are as follows:
 characterOffsetBegin: 0
 characterOffsetEnd: 5

When the same text is run through python, the offsets calculated are:
 startOffset: 0
 endOffset: 3

On debugging, i found that this is happening because corenlp being built using JAVA calculates string length using the code units of character and not the code points whereas PYTHON calculates string length using the code points. 

Due to this, for some of the cases where such special characters exist, the system fails as python tries to access offsets in string which may not be actually present. 

Is it possible to handle such cases by calculating the offsets in corenlp using code points so that the offset can be consumed in any language or any other solution ?

**Comment by AngledLuffa** [comment] 2020-02-10 17:01
Are you using utf-8 on both sides?

**Comment by kunalsawhney** [comment] 2020-02-11 08:48
Yes, the default encoding is set to utf-8 for both java and python.

**Comment by AngledLuffa** [comment] 2020-02-11 17:38
It will make my life significantly easier if you can send short snippets
which recreate the error.  Thanks!

**Comment by kunalsawhney** [comment] 2020-02-12 06:18
@AngledLuffa Below is the code snippet.

# Snippet to get tokenized version of text using CORENLP server:

```
from pycorenlp import StanfordCoreNLP

nlp = StanfordCoreNLP('http://localhost:9000')

text = 'I am 𝒚̂𝒊 random text'

output = nlp.annotate(
    text,
    properties={
        'annotators': 'tokenize,ssplit',
        'outputFormat': 'json'
    }
)

print(output)
# {'sentences': [{'index': 0, 'tokens': [{'index': 1, 'word': 'I', 'originalText': 'I', 'characterOffsetBegin': 0, 'characterOffsetEnd': 1, 'before': '', 'after': ' '}, {'index': 2, 'word': 'am', 'originalText': 'am', 'characterOffsetBegin': 2, 'characterOffsetEnd': 4, 'before': ' ', 'after': ' '}, {'index': 3, 'word': '𝒚̂𝒊', 'originalText': '𝒚̂𝒊', 'characterOffsetBegin': 5, 'characterOffsetEnd': 10, 'before': ' ', 'after': ''}]}]}

```



# Snippet to access the token in python using the character offsets returned by corenlp

```
for sent in output.get('sentences'):
    for token in sent.get('tokens'):
        token_start_offset = token.get('characterOffsetBegin')
        token_end_offset = token.get('characterOffsetEnd')
        print(text[token_start_offset:token_end_offset])

# Output
I
am
𝒚̂𝒊 r
ndom t
xt

```


As you can see from above, the tokens retrieved using the character offsets returned by corenlp are incorrect.

**Comment by kunalsawhney** [comment] 2020-02-23 06:30
@AngledLuffa Hi, Is there is any update on the issue ?

**Comment by AngledLuffa** [comment] 2020-02-27 23:50
The problem is Java considers that one character to have a width of 2.

```
public class foo {
  public static void main(String[] args) {
    String foo = "Z";
    System.out.println(foo);
    System.out.println(foo.length());

    foo = "我";
    System.out.println(foo);
    System.out.println(foo.length());

    foo = "𝒊";
    System.out.println(foo);
    System.out.println(foo.length());
  }
}
```

Z 1
我 1
𝒊 2

I guess it should be possible to detect that in Java using
Character.isLowSurrogate.  No idea how easy it is to detect it in Python.

**Comment by AngledLuffa** [comment] 2020-03-02 21:01
Actually, rereading the original issue, i guess you already knew it's codepoints instead of java characters causing the problem.  I will try to add functionality on the java side to return codepoints if requested, in which case the downstream app such as a python library can use the codepoints

**Comment by kunalsawhney** [comment] 2020-03-03 06:37
Hey, 
Getting codepoints in the response would not solve the issue. The issue is the calculation difference of length between java and python. 

In java, using `string.length()` returns the number of codeunits (used to represent code points), whereas in python `len(string)` returns the number of codepoints. 
However, using `string.codePointCount()` in java returns the length in terms of codepoints which matches the python length.

Can a functionality be added to calculate the `characteroffsets` of token original text using the codePointCount ?

**Comment by AngledLuffa** [comment] 2020-03-03 06:57
What I meant was I will return the # of codepoints.  That sounds like exactly what you just asked for

**Comment by kunalsawhney** [comment] 2020-03-03 07:04
Sorry, i got confused. Yes, the number of codepoints in the response would work. It would be great.

Just to confirm once, the updated response containing codepoints would be available when accessing through HTTP server, right ?

**Comment by AngledLuffa** [comment] 2020-03-03 07:05
That's the plan.  Gotta add that part still

**Comment by kunalsawhney** [comment] 2020-03-03 07:29
Alright. This sounds perfect.
is there anything I can help with to speed up the development for this functionality ?

**Comment by AngledLuffa** [comment] 2020-03-03 07:34
Nothing comes to mind

**Comment by kunalsawhney** [comment] 2020-03-04 07:05
Hi @AngledLuffa. 

I was working on the logic to use codepoints that will eventually be returned by the corenlp API. I noticed that just the number of codepoints would not solve the issue. I did not realise this before, apologies for that.

Ideally, what i need is the character offsets that are returned be calculated using the number of code points. 

for example, consider the string "𝒊". 
the length of "𝒊" according to java is 2 but the codepoints(used for len by other languages) are 1. 

So the ideal response is: 
`"tokens": [
        {
          "index": 1,
          "word": "𝒊",
          "originalText": "𝒊",
          "characterOffsetBegin": 0,
          "characterOffsetEnd": 1,
          "pos": "NN",
          "before": "",
          "after": ""
        }
      ]`  
and not 
`"tokens": [
        {
          "index": 1,
          "word": "𝒊",
          "originalText": "𝒊",
          "characterOffsetBegin": 0,
          "characterOffsetEnd": 2,
          "pos": "NN",
          "before": "",
          "after": ""
        }
      ]`

Is something like this possible ?

**Comment by AngledLuffa** [comment] 2020-03-04 07:23
I think there might be a miscommunication.  The feature I added to the
corenlp server returns exactly the numbers you just proposed.  Hopefully it
will be released soon, at which point we can add it to the stanfordnlp side
as well.  We can't change characterOffsetBegin/End, but we're going to name
it codepointOffsetBegin/End

**Comment by kunalsawhney** [comment] 2020-03-04 07:47
Okay. That's perfect. I maybe misunderstood it before. 
codepointOffsetBegin/End is what we would need.

Thanks for the quick support from your side.

**Comment by AngledLuffa** [comment] 2020-04-21 21:26
If you download corenlp 4.0.0 and stanza 1.0, you should now be able to use
the option `tokenize.codepoint: true` in your properties dictionary and get
back the codepoint offsets we discussed.

**Closed by AngledLuffa** 2020-04-21 21:26 UTC
