### ISSUE TITLE
The sentiment output result from -stdin differs from the when input is read from a file

### ISSUE THREAD

**Issue by paris007** [stanfordnlp/CoreNLP#105] opened 2015-11-19 20:49 UTC
I am not sure whether this issue is related to how the sentiment tool works or it is just a weird thing that stdin does. Regardless, I thought I should bring this up as a point of awareness for researchers analyzing the output results. 

Here is a toy snapshot of a comment from reddit analyzed via -stdin vs. being read from a .txt file. Please find the differences: 

<img width="1338" alt="screen shot 2015-11-19 at 12 49 22 pm" src="https://cloud.githubusercontent.com/assets/7051103/11283941/02125028-8ebc-11e5-9cc7-ac3bd9fa8fa5.png">

**Comment by manning** [comment] 2015-11-21 16:17
Closing as duplicate of #106

**Closed** 2015-11-21 16:17 UTC
Labels: duplicate
