### ISSUE TITLE
CoreNLP crashes with a "No roots in graph" RuntimeException

### ISSUE THREAD

**Issue by brendano** [stanfordnlp/CoreNLP#55] opened 2015-01-30 22:49 UTC
I have a sentence that gives a RuntimeException based on what I'm presuming is a bad or unexpected parse when trying to do dependency conversion with the `getFirstRoot()` call.  This sounds like an NLP problem and not a system engineering problem, so ideally, it would return null, or maybe a checked exception?  Using the shift-reduce parser and version 3.5.1 I get the message

```
java.lang.RuntimeException: No roots in graph:
dep                 reln                gov                 
---                 ----                ---                 

	at edu.stanford.nlp.semgraph.SemanticGraph.getFirstRoot(SemanticGraph.java:773)
```

The text I'm parsing is the following.  This is in JSON encoding.  Sorry I don't know which sentence is causing it.
```
"days has elapsed after the \nreport is received. As used in this subsection--\n            ``(1) the term `legislative day means any calendar day on         which the House of Representatives is in session; and            ``(2) the terms `rule and `regulation mean a provision or         series of interrelated provisions stating a single, separable         rule of law..    (b) Report on Using Voter Communication Vouchers for Primary Elections.--The Commission shall submit to the House of Representa"
```

in plaintext,

```
days has elapsed after the 
report is received. As used in this subsection--
            ``(1) the term `legislative day means any calendar day on         which the House of Representatives is in session; and            ``(2) the terms `rule and `regulation mean a provision or         series of interrelated provisions stating a single, separable         rule of law..    (b) Report on Using Voter Communication Vouchers for Primary Elections.--The Commission shall submit to the House of Representa
```

**Comment by brendano** [comment] 2015-01-30 22:55
to be clear i'm running an entire corenlp pipeline on this text.  my ini file is

```
annotators = tokenize,ssplit,pos,lemma,parse
parse.model = edu/stanford/nlp/models/srparser/englishSR.ser.gz
```

using jar files

stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1.jar
stanford-corenlp-full-2015-01-30/stanford-corenlp-3.5.1-models.jar
stanford-srparser-2014-10-23-models.jar

**Comment by AngledLuffa** [comment] 2015-02-20 19:33
I'm not able to reproduce this.  Is there anything more you can tell us
about the error?

**Comment by brendano** [comment] 2015-02-20 19:42
OK I re-ran it.

The crash is from this line (when I remove the try/except protection): https://github.com/brendano/stanford_corenlp_pywrapper/blob/b8b940b04ed83dc24b51598c9a172ebba31892d7/stanford_corenlp_pywrapper/javasrc/corenlp/Parse.java#L190

Looking at the parse output, I think it's for a sentence with a single word "." and parse tree (ROOT (NP (. .)))

**Comment by AngledLuffa** [comment] 2015-04-27 07:45
... seems to have gone away.  Perhaps the latest dependency rewritings have
fixed this

**Comment by manning** [comment] 2015-06-24 05:15
Agree. Seems fixed now.

**Closed by manning** 2015-06-24 05:15 UTC
