### ISSUE TITLE
Sentence splitting on particular complex words

### ISSUE THREAD

**Issue by grale88** [stanfordnlp/CoreNLP#1261] opened 2022-03-28 09:03 UTC
We have a following situation when using CoreNLP sentence detection. In the transcript we have some technology specific words like "Node.js" where CoreNLP recognizes sentence split. "Node" is the end of the sentence and "js" is the beginning of the next one. The transcript is in French. We created similar test with a sentence in English and here it does not happen. We tried using online CoreNLP demo and here are the results:

**French:**

Part of the transcript:
Une brève histoire du nudge par l'unité Node.js du groupe BVA Société d'études et de conseil.

![image](https://user-images.githubusercontent.com/42699404/160363010-0ead3db3-1400-4df2-ba78-2f83dab8f3af.png)

**English**

Example: This is an example text containing Node.js for testing purposes. Sentence splitting should work Ok here.

![image](https://user-images.githubusercontent.com/42699404/160363339-3f178743-abb3-431e-a62a-5eb112abd7f3.png)

We tried using `ssplit.tokenPatternsToDiscard` and `ssplit.boundariesToDiscard` properties for French language, but no changes were made to sentence detection output.

**Comment by AngledLuffa** [comment] 2022-04-03 03:51
I think we can probably incorporate the filename processing from PTBLexer
to FrenchTokenizer, but there's some other behavior in the tokenizers which
needs to be unified first.  Let me discuss with my PI

https://github.com/stanfordnlp/CoreNLP/pull/1265

... That's not quite complete yet, but theoretically you could build a
package out of that branch and start using it if this is blocking you

**Comment by grale88** [comment] 2022-04-14 19:25
Hi @AngledLuffa . Thank you for the reply. It is not a blocker for now. We will keep on following the progress on the PR.

**Comment by AngledLuffa** [comment] 2022-04-14 19:57
The issue is fixed on dev specifically for French, although we should probably generalize it to all of our jflex languages and should also incorporate the one/multi line changes from the other tokenizers

**Closed** 2022-07-24 17:22 UTC
Labels: tokenize, fixed on dev
